package SimulatedAnnealingBuilderInterfaces;

import StopConditionChecker.StopOuterLoopConditionChecker;

public interface NeedStopOuterLoopConditionChecker {
    NeedInnerLoopLength stopOuterLoopConditionChecker(StopOuterLoopConditionChecker stopOuterLoopConditionChecker);
}
